[workspace]
members = [
  "lang",
  "lang/macros/*",
  "lang/attribute/*",
  "lang/derive/*",
  "lang/common",
  "lang/spl/*",
  #"lang/syn",
]
exclude = ["examples"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Levi Bland <levi@arcane.fi>"]
repository = "https://github.com/arcane-fi/hayabusa"
rust-version = "1.89"
description = "Hayabusa: lightweight Solana runtime framework."

[workspace.dependencies]
bytemuck = "1.21.0"
borsh = { version = "=1", default-features = false }
borsh-derive = { version = "=1", default-features = false }
pinocchio-log = "0.5.1"
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.5.0"
syn = "2.0"
solana-address = "2.6"
solana-program-error = "3.0"
solana-define-syscall = "5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"
hayabusa = { path = "lang/hayabusa" }
hayabusa-common = { path = "lang/common" }
hayabusa-spl-token = { path = "lang/spl/token" }
hayabusa-spl-token-common = { path = "lang/spl/token-common" }
hayabusa-err-macro = { path = "lang/macros/err-macro" }
hayabusa-account-attribute = { path = "lang/attribute/hayabusa-account-attribute" }
hayabusa-discriminator-derive = { path = "lang/derive/hayabusa-discriminator-derive" }
hayabusa-impl-dyn-account-macro = { path = "lang/macros/impl-dyn-account-macro" }
hayabusa-program-attribute = { path = "lang/attribute/hayabusa-program-attribute" }
hayabusa-parse-accounts-derive = { path = "lang/derive/hayabusa-parse-accounts-derive" }
hayabusa-invoke-cpi-macros = { path = "lang/macros/invoke-cpi-macros" }
