[package]
name = "counter-program"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["idl-build"]
no-entrypoint = []
idl-build = ["hayabusa/idl-build"]

[dependencies]
bytemuck.workspace = true
hayabusa.workspace = true
hayabusa-token.workspace = true
